#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring files..."

ynh_restore_everything
#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

mkdir -p /var/log/"$app"
set_permissions

systemctl enable "$app".service --quiet
yunohost service add "$app" --description=XWiki --log="/var/log/$app/$app.log"

ynh_config_add_logrotate "/var/log/$app"

#=================================================
# RELOAD NGINX AND THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action=start --log_path=systemd --wait_until="$systemd_match_start_line"
wait_xwiki_started

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
